comments/urls.py
from django.urls import path,include
from .views import BlogView,Reply

app_name = 'comments'

urlpatterns = [
    path('test/<int:pk>',BlogView.as_view(),name='test'),
    path('replyto/<int:blog_id>/<int:comment_id>',Reply.as_view(),name='reply')
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/',include('comments.urls')),
    path('user/',include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include

urlpatterns = []

comments/models.py
from django.db import models
from user.models import User

class Blog(models.Model):
    blog = models.TextField(verbose_name='content')

class comments(models.Model):
    parent = models.ForeignKey('self',default=None,blank=True,null=True,on_delete=models.SET_NULL,related_name='children',verbose_name="parent")
    user = models.ForeignKey(User,to_field='username',blank=True,null=True,on_delete=models.SET_NULL)
    related_blog = models.ForeignKey(Blog,to_field='id',on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Comment')

    class Meta:
        ordering = ['parent__id']

    def __str__(self):
        return str(self.id)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    nickname = models.CharField(max_length=50,verbose_name="Nick Name",default='User')

comments/forms.py
from django import forms
from .models import comments

class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = comments
        fields = ['text','user','related_blog','parent']
        exclude = ['user','related_blog','parent']

comments/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,DetailView,View
from django.views.generic.edit import FormMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Blog,comments
from user.models import User
from .forms import CommentCreationForm

class BlogView(FormMixin,DetailView):
    template_name = 'comments/test.html'
    context_object_name = 'blog'
    form_class = CommentCreationForm

    def get_object(self):
        return get_object_or_404(Blog,pk=self.kwargs.get('pk'))

    def get_context_data(self, *args, **kwargs):
        context = super(BlogView, self).get_context_data(*args, **kwargs)
        context['usercomments'] = comments.objects.filter(related_blog=self.object)
        context['form'] = self.get_form()
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self,form):
        form.instance.user = User.objects.get(pk = self.request.user.pk)
        form.instance.related_blog = self.object
        form.save()

        return super(BlogView, self).form_valid(form)        
    
    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER', '/')
    
class Reply(FormMixin,View):
    form_class = CommentCreationForm
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self,form):
        form.instance.user = User.objects.get(id = self.request.user.id)
        form.instance.related_blog = get_object_or_404(Blog,id = self.kwargs.get('blog_id'))
        form.instance.parent = get_object_or_404(comments,id = self.kwargs.get('comment_id'))
        form.save()

        return super(Reply, self).form_valid(form)
    
    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER', '/')

user/views.py
from django.shortcuts import render

# Create your views here.

templates/comments/comment_loop.html
{% for usercomment in usercomments %}
    <div class="d-flex flex-start mt-4">
        <a class="me-3" href="#">
            <img class="rounded-circle shadow-1-strong"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(11).webp" alt="avatar"
                width="65" height="65" />
        </a>
        <div class="flex-grow-1 flex-shrink-1">
            <div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="mb-1">
                        {{usercomment.user}}
                    </p>
                </div>
                <p class="small mb-0">
                    {{usercomment.text}}
                </p>
            </div>
          
            <!--Form with blog id and comment id-->
            {% include 'comments/form.html' with blog_id=usercomment.related_blog.id comment_id=usercomment.id %}

            {% if usercomment.children.exists %}
                <a data-bs-toggle="collapse" href="#multiCollapse{{usercomment.id}}" role="button" aria-expanded="false" aria-controls="multiCollapse{{usercomment.id}}">
                    Show replies
                </a>
                <div class="collapse multi-collapse" id="multiCollapse{{usercomment.id}}">
                    <div class="card card-body">
                        {% include 'comments/comment_loop.html' with usercomments=usercomment.children.all form=form %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}

templates/comments/form.html
{% load crispy_forms_tags %}


<div class="dropdown">
    <a href="#" class="dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fas fa-reply fa-xs"></i>
        <span class="small"> 
            reply
        </span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li>
            <span class="dropdown-item-text">
                <form class="form-group" method="post" enctype="multipart/form-data" action="{% url 'comments:reply' blog_id comment_id %}">
                    {% csrf_token %}
                    <h4>Post your Reply</h4>
                    <div class="form-group mb-4">
                        {{ form|crispy }}
                    </div>
                    <div class="d-flex">
                        <div class="mx-auto">
                            <input type="submit" value="Post">
                        </div>
                    </div>
                </form>
            </span>
        </li>
    </ul>
</div>

templates/comments/test.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="{% static 'comments/assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'comments/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: {% static 'comments/assets/img/post-bg.jpg' %}">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1>Man must explore, and this is exploration at its greatest</h1>
                        <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                        <span class="meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on August 24, 2023
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Post Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <p>{{ blog.blog }}</p>
                </div>
            </div>
        </div>

        <!--Comments Section-->
        <form class="form-group" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h4>Post your comment</h4>
            <div class="form-group mb-4">
                {{ form|crispy }}
            </div>
            <div class="d-flex">
                <div class="mx-auto">
                    <input type="submit" value="Post">
                </div>
            </div>
        </form>

        <div class="container mt-5">
            <div class="row d-flex justify-content-center">
                {% for usercomment in usercomments %}
                    {% if usercomment.parent == None %}
                        <div class="d-flex flex-start mt-4">
                            <a class="me-3" href="#">
                            <img class="rounded-circle shadow-1-strong"
                                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(11).webp" alt="avatar"
                                width="65" height="65" />
                            </a>
                            <div class="flex-grow-1 flex-shrink-1">
                            <div>
                                <div class="d-flex justify-content-between align-items-center">
                                <p class="mb-1">
                                    {{usercomment.user}} <span class="small">- 3 hours ago</span>
                                </p>
                                </div>
                                <p class="small mb-0">
                                {{usercomment.text}}
                                </p>
                            </div>
                            <!--Form with blog id and comment id-->
                            {% include 'comments/form.html' with blog_id=usercomment.related_blog.id comment_id=usercomment.id %}
                            {% if usercomment.children.exists %}
                            <a data-bs-toggle="collapse" href="#multiCollapse{{usercomment.id}}" role="button" aria-expanded="false" aria-controls="multiCollapse{{usercomment.id}}">
                                Show replies
                            </a>
                            <div class="collapse multi-collapse" id="multiCollapse{{usercomment.id}}">
                              <div class="card card-body">
                                {% include 'comments/comment_loop.html' with usercomments=usercomment.children.all form=form %}
                              </div>
                            </div>
                            {% endif %}
                            
                        </div>
                        
                        </div>
                        
                    {% endif %}
                {% endfor %}

            </div>
        </div>
        <!--End of Comments Section-->
    </article>
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'comments/js/scripts.js' %}"></script>
</body>
</html>